### ISSUE TITLE
Protect the main branch

### ISSUE THREAD

**Issue by beauremus** [fermi-controls/parameter_page_app#1]
I had a brain fart and committed AND PUSHED to the main branch when I intended to create a pull request. Protecting the main branch will defend us from ignoramuses like me.

**Comment by rneswold** [comment]
It's good to keep this in mind. We're in a rapid development phase, so the pull requests would be a big impediment. Once we have a useful core and people can start working on separate features, however, we should enable this option.

**Comment by beauremus** [comment]
I can't think of any reason that PRs slow things down.

They help with organizing.

I didn't feel limited with #2.

**Comment by rneswold** [comment]
John and I were doing Live Share on VSCode and it seemed I was doing a lot of commits and pushes so John got the latest stuff. That was probably not the best workflow.

**Comment by beauremus** [comment]
We've agreed to support multiple paths to commit code to this repo. We have no plans right now to protect any branches.
